# merge-tools.TOOL.edit-args = ["$left", "$right", "$output"]
# snapshot.max-new-file-size = "10M"

[user]
name = "Phil Denhoff"
email = "phil@denhoff.ca"

[ui]
#diff-editor = ["scm-diff-editor", "--dir-diff", "$left", "$right"]
# diff.tool = ["difft", "--color=always", "$left", "$right"]
editor = "hx"
#pager = "delta"
pager = ["sh", "-c", "delta | less -RFX"]
default-command = "log"
diff-editor = ":builtin"

[revset-aliases]
'mine' = 'main@origin..author(phil)'
