# Starship config file
format = "$all"

[swift]
disabled=true

[custom.jj]
description = "Show the current jj revision"
command = 'jj log -T "change_id.shortest()" -r "@" --no-graph --ignore-working-copy'
#detect_folders = [".jj"]
when = 'jj root | grep -q "^/"'
symbol = "◉ "
style = 'bold purple'
format = 'on [$symbol$output]($style) '

