import = [
  "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
blur = true

[font]
normal = { family = "IosevkaTerm Nerd Font Mono", style = "Light" }
italic = { family = "IosevkaTerm Nerd Font Mono", style = "Light Oblique" }
bold = { family = "IosevkaTerm Nerd Font Mono", style = "SemiBold" }
bold_italic = { family = "IosevkaTerm Nerd Font Mono", style = "SemiBold Oblique" }
size = 14

[keyboard]
bindings = [
  { key= "Back", mods= "Command", chars= "\u0017" }
]
